// Map a local image path to its optimized WebP variant (generated by
// scripts/optimize-images.mjs). Remote/unknown paths pass through unchanged.
//   "small" → 480px wide WebP (cards, gallery thumbnails)
//   "main"  → 1366px wide WebP (gallery hero frame)
export function optImg(src: string | undefined, size: "small" | "main"): string {
  if (!src) return "";
  if (!src.startsWith("/assets/")) return src; // remote (e.g. rentals CDN) or other
  if (/\.svg$/i.test(src)) return src;
  const w = size === "small" ? 480 : 1366;
  return "/_img" + src.replace(/\.(jpe?g|png|webp)$/i, "") + "-" + w + ".webp";
}

// srcset over both generated widths, so cards don't download the 1366px
// variant on phones. Returns undefined for remote/SVG paths (no variants).
export function optImgSrcset(src: string | undefined): string | undefined {
  if (!src || !src.startsWith("/assets/") || /\.svg$/i.test(src)) return undefined;
  const base = "/_img" + src.replace(/\.(jpe?g|png|webp)$/i, "");
  return `${base}-480.webp 480w, ${base}-1366.webp 1366w`;
}

// How wide a card image actually renders: full-width on phones, half on
// tablets, a ~420px grid cell on desktop.
export const CARD_SIZES = "(max-width: 720px) 92vw, (max-width: 1080px) 46vw, 420px";

// Social-share variant of a cover photo (generated by optimize-images.mjs).
// WhatsApp drops og:images over ~600 KB, and many cover originals are
// multi-MB — so og:image must point at the ~1200px JPEG, never the original.
export function ogImg(src: string | undefined): string {
  if (!src || !src.startsWith("/assets/") || /\.svg$/i.test(src)) return src || "";
  return "/_img" + src.replace(/\.(jpe?g|png|webp)$/i, "") + "-og.jpg";
}
