// Map a local image path to its optimized WebP variant (generated by
// scripts/optimize-images.mjs). Remote/unknown paths pass through unchanged.
//   "small" → 480px wide WebP (cards, gallery thumbnails)
//   "main"  → 1366px wide WebP (gallery hero frame)
export function optImg(src: string | undefined, size: "small" | "main"): string {
  if (!src) return "";
  if (!src.startsWith("/assets/")) return src; // remote (e.g. rentals CDN) or other
  if (/\.svg$/i.test(src)) return src;
  const w = size === "small" ? 480 : 1366;
  return "/_img" + src.replace(/\.(jpe?g|png|webp)$/i, "") + "-" + w + ".webp";
}
